language: python
python: "3.6"
install:
    - pip install -r requirements_dev.txt
services:
    - xvfb
script:
    - pytest -k test_when_a_charged_battery_is_present_the_test_is_started
after_success:
    - coveralls