language: python
python: "3.6"
install:
    - pip install -r requirements_dev.txt
services:
    - xvfb
script:
    - pip install coverage==4.5.4
    - pytest --cov=battery_tester tests/
after_success:
    - coveralls